apiVersion: v1 # apiVersion - defines what type of objects we can use
kind: Pod      # Pod - type of object to run closely related containers
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
  - name: client
    image: nanamin0220/multi-client # should be on docker hub
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000


