apiVersion: v1
kind: Service      # setup networking in a k8s cluster
metadata:
  name: client-node-port
spec:
  type: NodePort   # exposes a container to the outside world (only good for dev, not for prod!!)
  selector:
    component: web
  ports:
  - port: 3050
    targetPort: 3000
    nodePort: 31515
