name: Deploy Multi-Docker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t nanamin0220/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true nanamin0220/react-test npm test

      - run: docker build -t nanamin0220/multi-docker-client:latest ./client
      - run: docker build -t nanamin0220/multi-docker-nginx:latest ./nginx
      - run: docker build -t nanamin0220/multi-docker-server:latest ./server
      - run: docker build -t nanamin0220/multi-docker-worker:latest ./worker

      - run: docker push nanamin0220/multi-docker-client:latest
      - run: docker push nanamin0220/multi-docker-nginx:latest
      - run: docker push nanamin0220/multi-docker-server:latest
      - run: docker push nanamin0220/multi-docker-worker:latest

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-ap-northeast-1-953201013282
          region: ap-northeast-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
